name: Unit Test

on:
    push:
        branches:
            - master

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [ 14, 16, 18 ]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: ${{matrix.node}}
            
            - name: Install dependencies
              uses: npm install

            - name: Run jest test
              run: npx jest --coverage
            
            - name: Upload test results
              uses: actions/upload-artifact@v2
              with:
                name: test-results
                path: ./coverage
